### ISSUE TITLE
Discuss Carry-Trade Opportunity Cost w/ Bas

### ISSUE THREAD

**Issue by jyrc** [AbrahamVermeulen1999/euro-zlotty-carry-trade#1]

**Comment by AbrahamVermeulen1999** [comment]
Dr. Campbell will discuss this with Bas following the first presentation.

**Comment by jyrc** [comment]
I just sent an e-mail to Bas requesting clarification of his comment.

**Comment by jyrc** [comment]
Bas replied that he is comfortable with the excess returns as they are defined in the paper, so long as they are _arithmetic_ returns rather than _logarithmic_ returns. Therefore, all of the results should be reported using arithmetic returns.
